---
name: Build and push

on:
  workflow_dispatch:
  inputs:
    file_name:
      description: "name of json file that will be created"
      required: false
      default: "output"
    file_dir:
      description: "directory where json file will be created"
      required: false
      default: "are_pids_prime"
    confirm:
      description: |
        Please confirm this action with message : 'Build'
      required: true


jobs:
  push:
    name: Build and push
    runs-on: [self-hosted]
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest
